### PR TITLE
fix: grant: respect dynamic options

### LINKED ISSUE #502: Organization id not being forwarded to WorkOS
WorkOS login does not work anymore.

From what I can see the issue is that Nhost endpoint `signin/provider/Workos?organization=XXX` redirects to 
```
https://api.workos.com/sso/authorize?client_id=XXX&response_type=code&redirect_uri=XXX
```
which is missing the organization parameter. Changing this manually to
```
https://api.workos.com/sso/authorize?client_id=XXX&organization=XXX&response_type=code&redirect_uri=XXX
```
solves the issue, and redirects me to the proper IdP login screen.

In v 0.20.1 and the organization parameter used to be added, while switching to v 0.24.1, without changing any of the configuration, makes this not work anymore.

The organization id is sent through the nhost sdk like this
```
nhost.auth.signIn({
  provider: 'workos',
  options: {
    organization: orgId,
  },
})
```

### PR DESCRIPTION
**Pull request by dbarrosop**
Fixes #502

### CODE REVIEW

File: src/routes/oauth/index.ts [hunk 1]
```diff
@@ -150,11 +150,15 @@ export const oauthProviders = Router()
    * @see {@link file://./config/index.ts}
    */
   .use((req, res, next) => {
-    res.locals.grant = {
-      dynamic: {
-        origin: `${req.protocol}://${req.hostname}`,
-      },
-    };
+    if (!res.locals.grant) {
+        res.locals.gran = {};
```
Comment (onehassan) [inline src/routes/oauth/index.ts:154]:
```suggestion
        res.locals.grant = {};
```

**Review by onehassan — APPROVED** [review]
